### ISSUE TITLE
hash error when starting ext_coldet download

### ISSUE THREAD

**Issue by KevinCain** [nmoehrle/mvs-texturing#18] opened 2015-07-20 20:37 UTC
After cloning mvs-texturing via git and successfully building cmake scripts, running `make` reports the hash error shown below:

insight@basilisk:~/mvs-texturing/build$ make
Scanning dependencies of target ext_coldet
[  1%] Creating directories for 'ext_coldet'
[  3%] Performing download step (download, verify and extract) for 'ext_coldet'
-- downloading...
     src='http://downloads.sourceforge.net/project/coldet/coldet/2.0/coldet20.zip'
     dst='/home/insight/mvs-texturing/build/elibs/coldet/src/coldet20.zip'
     timeout='none'
CMake Error at /home/insight/mvs-texturing/build/elibs/coldet/src/ext_coldet-stamp/download-ext_coldet.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/insight/mvs-texturing/build/elibs/coldet/src/coldet20.zip]
      expected hash: [37646a7dd046d9c81fca9d55346a108a]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]

elibs/CMakeFiles/ext_coldet.dir/build.make:82: recipe for target 'elibs/coldet/src/ext_coldet-stamp/ext_coldet-download' failed
make[2]: *** [elibs/coldet/src/ext_coldet-stamp/ext_coldet-download] Error 1
CMakeFiles/Makefile2:79: recipe for target 'elibs/CMakeFiles/ext_coldet.dir/all' failed
make[1]: *** [elibs/CMakeFiles/ext_coldet.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KevinCain** [comment] 2015-07-20 22:04
I found I needed to invoke both cmake and make as root; I was able to successfully compile the binaries using the canonical steps below:

git clone https://github.com/nmoehrle/mvs-texturing.git
cd mvs-texturing
mkdir build && cd build
Generate make file
cmake ..
make

**Comment by nmoehrle** [comment] 2015-07-22 16:25
Had the same error once today and think I can remember having it before, but I am not been able to reproduce it. It should not be necessary to run cmake and make with root and I would advise against it.
Running make again worked for me, but I would love to find out if this is simply a network hiccup or something else.
Are you able to reproduce the error?

**Comment by KevinCain** [comment] 2015-07-22 17:06
I had avoided running as root, likely for the same reasons as you.

I will try to reproduce the error and forward the context.

**Comment by flxshujie** [comment] 2015-09-22 13:04
I found it has some problems in the step "make -j8 -C fssr" ,it report " mesh_clean.cc:41:5: error: ‘MeshVertexInfo’ is not a member of ‘mve’  mve::MeshVertexInfo& vinfo2 = vinfos[v2];
mesh_clean.cc:41:26: error: ‘vinfo2’ was not declared in this scope mve::MeshVertexInfo& vinfo2 = vinfos[v2];" ,I donot know why it didnot have problem ever ,did you changed the source code ?

**Comment by nmoehrle** [comment] 2015-09-22 13:30
The MVE api changed  I am on it

**Comment by flxshujie** [comment] 2015-09-22 14:01
I am do some research in texture , I have read your code ,I have some questions about the "TexturePatch::adjust_colors(adjust_values)" because I changed some codes in the project ,so I want to download the new project to know how to change in the patch . could you tell me how to compile the latest project.QQQ

**Comment by nmoehrle** [comment] 2015-09-22 14:24
The last commit(346d0d0) fixes the issue.
Please do not post things unrelated to the issue at hand (#18).
If you encounter problems which are unrelated to any existing issues, please open up a new issue.

**Comment by nmoehrle** [comment] 2015-10-05 11:54
Since no one has been able to observe the hash mismatch for a couple of months now, I will close the issue.

**Closed by nmoehrle** 2015-10-05 11:54 UTC
