### ISSUE TITLE
Texturing stage fails

### ISSUE THREAD

**Issue by pmd3sallijr** [nmoehrle/mvs-texturing#165] opened 2021-01-13 17:59 UTC
Hi,
I'm using Regard 3D and trying to texture a model from 175 registyed images. The laptop has 48Gb RAM and a 4GB GPU. The problem is the texturing stage always fails. I have looked at the CPU?GPU usage during the texturing and although the CPU is 80-100% the GPU is barly tpouched. It is also using all 48GB RAM. Why is this no running to completion? Any help wouyld be much appreciated.

**Comment by nmoehrle** [comment] 2021-06-03 08:54
Duplicate of #166

**Closed by nmoehrle** 2021-06-03 08:54 UTC
